version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)

  build:
    commands:
      - echo Building server image...
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/server:$IMAGE_TAG -f server/Dockerfile ./server
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/server:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/server:latest

      - echo Building client image...
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/client:$IMAGE_TAG -f client/Dockerfile ./client
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/client:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/client:latest

  post_build:
    commands:
      - echo Pushing images to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/server:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/server:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/client:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/client:latest

      # Create or update ECS task definition using a template (task-definition-template.json)
      - echo Creating or updating the ECS task definition...
      - sed -e "s|<SERVER_IMAGE_TAG>|$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/server:$IMAGE_TAG|g" aws/backend-task-definition-template.json > aws/backend-final-task-definition.json
      - sed -e "s|<CLIENT_IMAGE_TAG>|$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/research-web-portal/client:$IMAGE_TAG|g" aws/frontend-task-definition-template.json > aws/frontend-final-task-definition.json

      # Register the updated task definition with ECS
      - aws ecs register-task-definition --family back-end --cli-input-json file://aws/backend-final-task-definition.json
      - aws ecs register-task-definition --family front-end --cli-input-json file://aws/frontend-final-task-definition.json

      # Update the ECS service to use the new task definition
      - echo Updating ECS service...
      - ecs_backend_service_name="back-end-service"
      - ecs_frontend_service_name="front-end-service"
      - ecs_cluster_name="TestCluster"

      - echo Checking if ECS Back End service exists...
      - if aws ecs describe-services --cluster $ecs_cluster_name --services $ecs_backend_service_name --query "services[0].status" --output text | grep -q ACTIVE; then
          echo "Service exists. Updating service...";
          backend_new_task_revision=$(aws ecs describe-task-definition --task-definition back-end --query "taskDefinition.revision" --output text);
          aws ecs update-service --cluster $ecs_cluster_name --service $ecs_backend_service_name --task-definition back-end:$backend_new_task_revision;
        else
          echo "Service does not exist. Creating new service...";
          aws ecs create-service --cluster $ecs_cluster_name --service-name $ecs_backend_service_name --task-definition back-end --desired-count 1 --launch-type FARGATE --network-configuration "awsvpcConfiguration={subnets=[subnet-064c82f7ca1de5647,subnet-09a8ab73135908b88,subnet-0cff645bf52ddd0ab],securityGroups=[sg-0e41078d7d83aa934,sg-0a12f949b5aaab0e5],assignPublicIp=ENABLED}";
        fi

      - echo Checking if ECS Front End service exists...
      - if aws ecs describe-services --cluster $ecs_cluster_name --services $ecs_frontend_service_name --query "services[0].status" --output text | grep -q ACTIVE; then
          echo "Service exists. Updating service...";
          frontend_new_task_revision=$(aws ecs describe-task-definition --task-definition front-end --query "taskDefinition.revision" --output text);
          aws ecs update-service --cluster $ecs_cluster_name --service $ecs_frontend_service_name --task-definition front-end:$frontend_new_task_revision;
        else
          echo "Service does not exist. Creating new service...";
          aws ecs create-service --cluster $ecs_cluster_name --service-name $ecs_frontend_service_name --task-definition front-end --desired-count 1 --launch-type FARGATE --network-configuration "awsvpcConfiguration={subnets=[subnet-064c82f7ca1de5647,subnet-09a8ab73135908b88,subnet-0cff645bf52ddd0ab],securityGroups=[sg-0e41078d7d83aa934,sg-0a12f949b5aaab0e5],assignPublicIp=ENABLED}";
        fi

artifacts:
  files:
    # - task-definition.json
    - aws/backend-task-definition-template.json
    - aws/backend-final-task-definition.json
    - aws/frontend-task-definition-template.json
    - aws/frontend-final-task-definition.json
