AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Stack for Research Web Portal dev environment

Mappings:
  taggingMap:
    stackType:
      key: stack
      dev: dev
      prod: prod

Resources:
  AppEnvSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: myapp/env
      Description: Environment variables for ECS task
      SecretString: !Sub |
        {
          "ACCESS_TOKEN_EXPIRY": "",
          "ADMIN": "",
          "BACKEND_URI": "",
          "DB_PROD_COLLECTION": "",
          "DB_DEV_COLLECTION": "",
          "EMAIL_PASSWORD": "",
          "EMAIL_USER": "",
          "FACULTY": "",
          "INDUSTRY": "",
          "NODE_ENV": "",
          "PORT": "",
          "REFRESH_TOKEN_EXPIRY": "",
          "ACCESS_TOKEN_SECRET": "",
          "REFRESH_TOKEN_SECRET": "",
          "STUDENT": "",
          "TEST_ADMIN_EMAIL": "",
          "TEST_ADMIN_PASS": "",
          "TEST_ADMIN_PASS_HASHED": "",
          "TEST_EMAIL_NAME": "",
          "TEST_EMAIL": "",
          "TEST_EMAIL_PASS": ""
        }
      Tags:
        - Key: !FindInMap [ taggingMap, stackType, key ]
          Value: !FindInMap [ taggingMap, stackType, dev ]