name: Node.js CI

on:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
  pull_request:
    branches: "main"

jobs:
  build:
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: server/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: "Move to server dir, Create env file, Install dependencies, Run tests"
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          PORT: ${{ vars.PORT }}
          DB_URI: ${{ secrets.DB_URI }}
          DB_PROD_COLLECTION: ${{ secrets.DB_PROD_COLLECTION }}
          DB_DEV_COLLECTION: ${{ secrets.DB_DEV_COLLECTION }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          REFRESH_TOKEN_EXPIRY: ${{ secrets.REFRESH_TOKEN_EXPIRY }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          ACCESS_TOKEN_EXPIRY: ${{ secrets.ACCESS_TOKEN_EXPIRY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          FRONT_END_URI: ${{ secrets.FRONT_END_URI }}
          ADMIN: ${{ vars.ADMIN }}
          STUDENT: ${{ vars.STUDENT }}
          FACULTY: ${{ vars.FACULTY }}
          INDUSTRY: ${{ vars.INDUSTRY }}
          TEST_ADMIN_EMAIL: ${{ secrets.TEST_ADMIN_EMAIL }}
          TEST_ADMIN_PASS: ${{ secrets.TEST_ADMIN_PASS }}
          TEST_ADMIN_PASS_HASHED: ${{ secrets.TEST_ADMIN_PASS_HASHED }}
          TEST_EMAIL_NAME: ${{ secrets.TEST_EMAIL_NAME }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_EMAIL_PASS: ${{ secrets.TEST_EMAIL_PASS }}
        run: |
          cd server
          npm install
          npm test
