name: Node.js CI

on:
  push:
    branches: 
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  pull_request:
    branches:  "main"

jobs:
  build:
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: server/package-lock.json
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: 'Move to server dir, Create env file, Install dependencies, Run tests'
      run: |
        cd server
        echo "${{ secrets.ENV }}" > .env
        npm install
        npm test
